{% set version = "1.15" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz
  sha256: 116f30b36f5c1df15cffbbfa4b5dc103d42e746d85d5b9f9c7c3bcc02155934a
  patches:
    - 0001-GLM-Fix-setOptimizationBounds.patch
    - 0001-GaussianNonLinearCalib-Fix-for-unobserved-inputs.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('openturns', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - boost-cpp
    - matplotlib-base
    - liblapack  # [not win]
    - libxml2  # [not win]
    - tbb-devel  # [not win]
    - hmat-oss  # [not win]
    - cminpack  # [not win]
    - ceres-solver  # [not win]
    - nlopt  # [not win]
    - dlib-cpp  # [not win]
    - coinbonmin  # [not win]
    - spectralib  # [not win]
  run:
    - python
    - psutil
    - tbb-devel  # [not win]

test:
  imports:
    - openturns

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
