{% set version = "1.7" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  git_url: https://github.com/jschueller/openturns.git
  git_tag: cotire

build:
  number: 201
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - matplotlib
    - cmake
    - swig
    - boost
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - libxml2
    - muparser
    - tbb
    - nlopt
    - hmat-oss

  run:
    - python
    - matplotlib
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - libxml2
    - muparser
    - tbb
    - nlopt
    - hmat-oss

test:
  imports:
    - openturns.viewer

about:
  home: http://openturns.org/
  license: LGPLv3
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
