{% set version = "1.9rc1" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz  # [not win]
  sha256: a04f19c7173fe509150bc648f26823cc8b8b09f9ff54f511540af84f434a069f  # [not win]

  fn: openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 539b2813bccfcb5645301562d24ce91b2f1f4908668576d58bf4169fa5fc82a6  # [win32 and py27]

  fn: openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 6f72b7de40481b51d172372c2519572449d4a6d46e0c0628c7ed1c05713c58c0  # [win64 and py27]

  fn: openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 328ee3b4c93748dfdf78232e683440007bbe8194168be4df9ffc0ad25c4e4da7  # [win32 and py35]

  fn: openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 69e979b99ceb8e2a98e400e23c6d158aae541675116b1fed370b43b7fc1b0137  # [win64 and py35]

  fn: openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  sha256: 0ac376102cac485168f572f7204f6d8efd556861cd6f0b15f4af2c0027ddd547  # [win32 and py36]

  fn: openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 9b4c27130432b6facea1161ba101a04d81877ab24fdc3db7c75c14e82f2faf61  # [win64 and py36]

build:
  number: 201
  features:
    - blas_{{ variant }}  # [not win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - boost-cpp 1.63.*  # [not win]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]
  run:
    - python  # [py<36]
    - python >= 3.6.1 # [py>=36]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]

test:
  requires:
    - matplotlib
  imports:
    - openturns
    - openturns.viewer

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
