{% set version = "1.10" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz  # [not win]
  sha256: a64f65c4e4b7062895e668b39af5d39ebb44528551571fcba07e55cbb7215658  # [not win]

  fn: openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: b01d11485663635f0e026f7f72de12df6fc27a31cfd0668813fb199230fbeb14  # [win32 and py27]

  fn: openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: cd397a0df0c20022da81e7a01a658201a886511c1fe53e2dc68eb30a925e8472  # [win64 and py27]

  fn: openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: c2e3d98a87ce59e9f23c5408e53ae525eaa7a18eb303c5166d65d6b482840744  # [win32 and py35]

  fn: openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: fbf6a636974a8b51d4c60ca7789e9a2b162ef4d60f06ad1513fc7195e8a02add  # [win64 and py35]

  fn: openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  sha256: 9fc2ef1f84235b58d51d9d7b71ad2737088ee8400fc77a5b791677014eefa427  # [win32 and py36]

  fn: openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 7646c20ab4d355c5b291d8f956af53e569da214377020a346cb3bc8f869dfbbc  # [win64 and py36]

  patches:
    - 0001-Use-numpy-legacy-printing-mode.patch  # [not win]

build:
  number: 202
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - boost-cpp 1.66.0  # [not win]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]
  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]

test:
  requires:
    - matplotlib
  imports:
    - openturns
    - openturns.viewer

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
