{% set version = "1.18" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz
  sha256: 1840d3fd8b38fd5967b1fa04e49d8f760c2c497400430e97623595ca48754ae0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('openturns', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
    - bison  # [not win]
  host:
    - python
    - boost-cpp  # [not win]
    - matplotlib-base
    - mpc  # [not win]
    - libblas  # [not win]
    - liblapack  # [not win]
    - libxml2  # [not win]
    - tbb-devel  # [not win]
    - hmat-oss  # [not win]
    - cminpack  # [not win]
    - ceres-solver  # [not win]
    - nlopt  # [not win]
    - dlib-cpp  # [not win]
    - coinbonmin  # [not win]
    - spectralib  # [not win]
    - hdf5  # [not win]
    - primesieve  # [not win]
  run:
    - python
    - dill
    - psutil
    - tbb-devel  # [not win]

test:
  imports:
    - openturns

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
