{% set version = "13.1.1" %}

package:
  name: persalys
  version: {{ version }}

source:
  fn: persalys-{{ version }}.tar.gz
  url: https://github.com/persalys/persalys/archive/v{{ version }}.tar.gz
  sha256: fe8c645707ad3a21b7c720fd50f2b1ccb5f10510d7ce5431d6ca9cdff3cba1b6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('persalys', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    #- {{ cdt('libglvnd-glx') }}          # [linux]
    #- {{ cdt('libglvnd-egl') }}          # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - boost-cpp
    - liblapack
    - qt-main
    - libxml2
    - qwt
    - hdf5
    - paraview
    - cli11
    - nlohmann_json
    - eigen
    - cminpack
    - expat
  run:
    - python
    - boost-cpp

test:
  imports:
    - openturns
    - otmorris
    - persalys

about:
  home: https://www.persalys.fr/?la=en
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Uncertainty treatment GUI

extra:
  recipe-maintainers:
    - jschueller
