{% set version = "1.11" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 0b5e572f0a1b3a7a73bc912836f2420bd565d606b3f6a62771cb998ad83eb47f  # [not win]

  fn: openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 01e01291f9949ecd1d7f1b1f091a650df6efa364752f58372de4829437b44adb  # [win64 and py27]

  fn: openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 7267aa71cb897113ff5e960166dbbe244b2410b38afd94ed40c88f38fc2de3f2  # [win64 and py35]

  fn: openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 8813d990165748e486904246250a0e059415e2583a239d235fd78e19bbd0e10f  # [win64 and py36]

  patches:
    - 0001-Fix-Cobyla-optimal-point-query.patch  # [not win]
    - 0001-Fix-Mesh-isRegular.patch  # [not win]

build:
  number: 202
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - cmake  # [not win]
    - swig  # [not win]
    - boost-cpp  # [not win]
    - tbb-devel  # [not win]
  host:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas  # [not win]
    - libxml2  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]
  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas  # [not win]
    - libxml2  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]

test:
  requires:
    - matplotlib
  imports:
    - openturns
    - openturns.viewer

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
