{% set version = "1.10.1" %}
{% set variant = "openblas" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  fn: openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build/releases/download/v{{ version }}/openturns-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 693551fd860b38fb0efef6ead4cee38c9b1f9e8fe4b1de7aa08700fed1eccba4

  patches:
    - 0001-Use-numpy-legacy-printing-mode.patch  # [not win]

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - boost-cpp 1.66.0  # [not win]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]
  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
    - libxml2 2.9.*  # [not win]
    - muparser  # [not win]
    - tbb  # [not win]
    - nlopt  # [not win]
    - hmat-oss  # [not win]

test:
  requires:
    - matplotlib
  imports:
    - openturns
    - openturns.viewer

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
