{% set version = "1.26" %}

package:
  name: openturns
  version: {{ version }}

source:
  fn: openturns-{{ version }}.tar.gz
  url: https://github.com/openturns/openturns/archive/v{{ version }}.tar.gz
  sha256: 624bd45f89ab3afe1931cb07f8c5398e6983faa40a1d92a81b04006f45b66147

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('openturns', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - m2-diffutils  # [win]
    - diffutils  # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - libboost-headers
    - matplotlib-base  # [python_impl == 'cpython']
    - mpc
    - libblas
    - liblapack
    - libxml2-devel
    - tbb-devel
    - cminpack
    - ceres-solver
    - glog
    - nlopt
    - dlib-cpp
    - ipopt
    - coin-or-bonmin  # [not win]
    - spectralib
    - hdf5
    - highs
    - pagmo-devel
    - libboost-devel
    - primesieve
    - libcuba
    - nanoflann
    - zlib
  run:
    - python
    - dill
    - psutil
    - tbb-devel
    - highs

test:
  imports:
    - openturns

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Uncertainty treatment library

extra:
  recipe-maintainers:
    - jschueller
