travis:
  secure:
    BINSTAR_TOKEN: penbQ5pHucsC+l2HHJPFH0FgcPHSVf1rI9VNIZEPPehJXe5MgK70N4g/DkjQL4Q2T+Rp2ziaoVjlcRtDUPu8h3yVYrgnMDxgpUFgAoYPx/9mBMUfs3wWv7GuJYF0llwwtRQkM8u2QXFG4i0/2Txxf8nFpmHQD0JaN5ArknddCvDIsgnATdBwbcLo1qkJiO2Z1BPbO1Jxe1ooXFZp4cnTq3zxha9aHZcmUb8bCXOicHEPBldjNxRxLjgfrH8IVNvKzWeocM8RkirZTC4VQ7+LMZlTCgfYODwLV6Sazng0RRLuLyXO9jWMDdby9sQSP2FplrisUTLiTqBdOg2n5cxujqBaxD7fjL2SnoWEC3wBYbqxBgz4fuGmiR2F96OvNiOrPIwSKdoYWwEhFchvMT3UksivGhmkhb/ajCE9fESg09CgeAWnL+m1rDrM9F4QI6Xeq8vM38fKrljxTHJ8Rv+GcfDzvEiWaL1RSKMPMTXsI2roUXMQY14vPBYt9FIPpTaNScxNyLXw3BhbouYZ85gU0Pn6/LUJDQ96IDorMk+iCiWyK6BhTOsmnpml/cgXi+iLMPuwEvZsYl4OIqaHu1hznnF6YFe8LXBUt2np8f7e1WY9xUs7lMvyXZ8tzGAFg2xs6a7P8IETo7+46a9IAD6yUj35Jbfd+nBB5+GM11zSJ7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
